import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ConvexClient } from "@/provider/ConvexClient";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sport Tournament App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClient>
          <Toaster/>
          {children}
        </ConvexClient>
      </body>
    </html>
  );
}
